package com.chenhao.musicplayer.bean;

/**
 * Created by chenhao on 2016/11/16.
 */

public enum ItemViewType {
    TYPE_BANNER,TYPE_SQUARE,TYPE_MVSQUARE,TYPE_KSQUARE,TYPE_KLIST,TYPE_LIST,TYPE_HEAD,TYPE_ARTIST,TYPE_ARTIST_HEAD
    ,TYPE_CLASSIFY,TYPE_MUSIC,TYPE_COMMENT,TYPE_MV
}